language: erlang
otp_release:
- 17.1
before_install:
- git clone https://github.com/elixir-lang/elixir
- cd elixir
- git checkout v1.0.2
- cd ..
- make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "yes | MIX_ENV=test mix do deps.get, compile, test"
